import { type Metadata } from "next";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import "@/styles/themes/stone.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background min-h-screen font-poppins antialiased",
          poppins.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
